# Generated by Django 5.0.14 on 2026-04-21 21:46

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=512, null=True),
        ),
    ]
