# Generated by Django 5.0.14 on 2026-04-21 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error_text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameIndex(
            model_name='magiclink',
            new_name='accounts_ma_email_308839_idx',
            old_name='accounts_ma_email_idx',
        ),
        migrations.AddField(
            model_name='userdataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdataexport',
            index=models.Index(fields=['user', '-created_at'], name='user_export_recent_idx'),
        ),
    ]
