# Generated by Django 5.0.14 on 2026-04-22 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiExtractionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_filename', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_bytes', models.BigIntegerField(default=0)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('running', 'Executando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_extr_recent_idx'), models.Index(fields=['status'], name='ai_extr_status_idx')],
            },
        ),
    ]
