# Generated by Django 5.0.14 on 2026-04-26 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tomador', models.CharField(blank=True, default='', max_length=255)),
                ('descricao_md', models.TextField(blank=True, default='')),
                ('requisitos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('fechada', 'Fechada')], default='ativa', max_length=16)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('requisicao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vaga', to='requisitions.requisicao')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-publicada_em'], name='vaga_status_pub_idx')],
            },
        ),
    ]
