# Generated by Django 5.0.14 on 2026-04-21 21:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('args_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped_duplicate', 'Skipped (Duplicate)')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['actor_name', 'args_hash', 'status'], name='core_jobexe_actor_n_244f22_idx')],
            },
        ),
    ]
