# Generated by Django 5.0.14 on 2026-04-21 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('summary_shown_version', models.CharField(blank=True, default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_acceptance',
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('terms', 'Termos de Uso'), ('privacy', 'Política de Privacidade')], max_length=16)),
                ('version', models.CharField(help_text='Semver, ex: 1.0.0', max_length=32)),
                ('effective_at', models.DateTimeField()),
                ('full_text_md', models.TextField()),
                ('summary_of_changes_md', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy_version',
                'indexes': [models.Index(fields=['kind', '-effective_at'], name='policy_kind_eff_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('kind', 'version'), name='policy_version_kind_version_unique'),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='policies.policyversion'),
        ),
        migrations.AddIndex(
            model_name='policyacceptance',
            index=models.Index(fields=['user', '-accepted_at'], name='policy_user_acc_idx'),
        ),
    ]
