# Generated by Django 5.0.14 on 2026-04-21 22:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_prev', models.CharField(max_length=64)),
                ('hash_curr', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='audit_entity_ts_idx'), models.Index(fields=['actor_user_id', 'timestamp'], name='audit_actor_ts_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditlog',
            constraint=models.UniqueConstraint(fields=('hash_curr',), name='audit_hash_curr_unique'),
        ),
    ]
