# Generated by Django 5.0.14 on 2026-04-26 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('payload_ia', models.JSONField(blank=True, default=dict, help_text='Snapshot dos campos extraídos pela IA — editável pelo RH.')),
                ('score_confianca', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em revisão'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='rascunho', max_length=16)),
                ('motivo_rejeicao', models.TextField(blank=True, default='')),
                ('ai_log', models.ForeignKey(blank=True, help_text='Log da extração IA que originou esta requisição (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='ai_providers.aiextractionlog')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='req_status_recent_idx'), models.Index(fields=['criado_por', '-created_at'], name='req_user_recent_idx')],
            },
        ),
    ]
